### PR TITLE
CQP update

### PR DESCRIPTION
**Pull request by lambe**
The complete set of updates to the regularlized quadratic interior-point method. These updates bring the solver up-to-date with the new NLPModel and SlackModel formulation. Benchmark results are comparable to those found in the reference paper. A driver file is included to demonstrate the interface with CUTEST.py.

### CODE REVIEW

**Comment by lambe** [comment]
It looks like the test failed because we can't import ma27 or ma57. We could add a download of HSL.py to the Travis CI script, but that package relies on external code, which might not be available to all users. Any suggestions?

**Comment by dpo** [comment]
At some point, @syarra wrote a simple LDL factorization for SQD matrices. The idea was to include it in NLP.py by default in case the user doesn't have access to HSL.py. I'm not sure what its status is. It would resolve the problem.

**Comment by dpo** [comment]
Here: https://github.com/PythonOptimizers/LLDL.py

**Comment by dpo** [comment]
Any ideas about this? Did you solve the issue in the least-squares solver?

**Comment by lambe** [comment]
I never followed up since I was using HSL the whole time. I'll make a note and update it when I get chance.

**Pull request closed without merging**
