### PR TITLE
Auglag

### PR DESCRIPTION
**Pull request by syarra**
auglag is back....

there is a bug with stopping criteria between TRON and auglag.
Needs more investigation.

### CODE REVIEW

**Comment by dpo** [comment]
Where does this stand?

**Comment by dpo** [comment]
Rebased.

**Comment by dpo** [comment]
I made a few local changes that fix some bugs. Among the equality-constrained problems in COPS, we're solving two sizes of `elec` and getting there on the third, but struggling on `chain` and `channel`. We need to pass appropriate stopping conditions to TRON in the inner loop!!!

**Comment by dpo** [comment]
This should probably be backtracked and rebased to include #72 cleanly.

**Comment by lambe** [comment]
It looks like this pull request is ready to close. There may be more bugs to fix, but Auglag works pretty well with all of the work to this point. I recommend merging into the develop branch.

**Comment by dpo** [comment]
Thanks all!

**Pull request merged**
